-- Criação da tabela Fornecedor
CREATE TABLE FORNECEDOR(
    FCODIGO INTEGER PRIMARY KEY,
    FNOME VARCHAR(50) NOT NULL,
    STATUS VARCHAR(10) DEFAULT 'ATIVO', -- STATUS padrão 'ATIVO'
    CIDADE VARCHAR(20) -- CIDADE do fornecedor
);

SELECT * FROM FORNECEDOR;

-- Criação da tabela Peça
CREATE TABLE PECA(
    PCODIGO INTEGER PRIMARY KEY,
    PNOME VARCHAR(50) NOT NULL,
    COR VARCHAR(10) NOT NULL, -- COR da peça
    PESO NUMERIC(7,2) NOT NULL, -- PESO da peça
    CIDADE VARCHAR(20) NOT NULL -- CIDADE onde a peça está localizada
);

SELECT * FROM PECA;

-- Criação da tabela Instituição
CREATE TABLE INSTITUCAO(
    ICODIGO INTEGER PRIMARY KEY,
    INOME VARCHAR(50) NOT NULL -- NOME da instituição
);

SELECT * FROM INSTITUCAO;

-- Criação da tabela Projetos
CREATE TABLE PROJETOS(
    PRCODIGO INTEGER PRIMARY KEY,
    PRNOME VARCHAR(50) NOT NULL, -- NOME do projeto
    PRCIDADE VARCHAR(20) NOT NULL, -- CIDADE onde o projeto está localizado
    ICODIGO INTEGER, -- ICODIGO da instituição associada ao projeto
    FOREIGN KEY (ICODIGO) REFERENCES INSTITUCAO
);

SELECT * FROM PROJETOS;

-- Criação da tabela Fornecimento
CREATE TABLE FORNECIMENTO(
    ID SERIAL PRIMARY KEY,
    FCODIGO INTEGER,
    PCODIGO INTEGER,
    PRCODIGO INTEGER,
    QUANTIDADE INTEGER,
    FOREIGN KEY(FCODIGO) REFERENCES FORNECEDOR,
    FOREIGN KEY(PCODIGO) REFERENCES PECA,
    FOREIGN KEY(PRCODIGO) REFERENCES PROJETOS
);

SELECT * FROM FORNECIMENTO;

-- ALTERAÇÕES (PARTE 02)

ALTER TABLE PROJETOS
	DROP FOREIGN KEY ICODIGO; -- Remove a chave estrangeira ICODIGO

ALTER TABLE PROJETOS
	DROP COLUMN ICODIGO; -- Remove a coluna ICODIGO

DROP TABLE INSTITUCAO; -- Remove a tabela INSTITUCAO

-- CRIAÇÃO DA TABELA CIDADE
CREATE TABLE CIDADE(
    CCOD INT NOT NULL,
    CNOME VARCHAR(30) NOT NULL,
    UF CHAR(2) NOT NULL,
    PRIMARY KEY (CCOD)
);

SELECT * FROM CIDADE;

-- ALTERAÇÃO NA TABELA FORNECEDOR
SELECT * FROM FORNECEDOR;

ALTER TABLE FORNECEDOR
	DROP COLUMN CIDADE; -- Remove a coluna CIDADE

ALTER TABLE FORNECEDOR
	ADD COLUMN FONE BIGINT NOT NULL; -- Adiciona a coluna FONE

ALTER TABLE FORNECEDOR
    ALTER COLUMN FONE TYPE BIGINT; -- Altera o tipo da coluna FONE para BIGINT

ALTER TABLE FORNECEDOR
	ADD COLUMN CCOD INT NOT NULL; -- Adiciona a coluna CCOD

ALTER TABLE FORNECEDOR
	ADD CONSTRAINT FK_CCOD_FORNECEDOR -- Adiciona uma chave estrangeira CCOD na tabela FORNECEDOR
    FOREIGN KEY (CCOD) REFERENCES CIDADE (CCOD);

ALTER TABLE FORNECEDOR
	DROP CONSTRAINT FK_CCOD_FORNECEDOR -- Remove a restrição de chave estrangeira FK_CCOD_FORNECEDOR
    FOREIGN KEY (CCOD) REFERENCES CIDADE (CCOD);

SHOW CREATE TABLE FORNECEDOR;

-- ALTERAÇÃO NA TABELA PECA
SELECT * FROM TBL_PECA;

ALTER TABLE TBL_PECA
	DROP COLUMN PCIDADE; -- Remove a coluna PCIDADE

ALTER TABLE TBL_PECA 
	ADD COLUMN CCOD INT NOT NULL; -- Adiciona a coluna CCOD

ALTER TABLE TBL_PECA
	ADD CONSTRAINT FK_CCOD_PECA -- Adiciona uma chave estrangeira CCOD na tabela PECA
    FOREIGN KEY (CCOD) REFERENCES TBL_CIDADE (CCOD);

-- ALTERAÇÃO NA TABELA PROJETO
SELECT * FROM TBL_PROJETO;

ALTER TABLE TBL_PROJETO
	DROP COLUMN CIDADE; -- Remove a coluna CIDADE

ALTER TABLE TBL_PROJETO
	ADD COLUMN CCOD INT NOT NULL; -- Adiciona a coluna CCOD

ALTER TABLE TBL_PROJETO
	ADD CONSTRAINT FK_CCOD_PROJETO -- Adiciona uma chave estrangeira CCOD na tabela PROJETO
    FOREIGN KEY (CCOD) REFERENCES TBL_CIDADE (CCOD);

    SELECT * FROM FORNECIMENTO;
